### ISSUE TITLE
咨询一下预训练的问题

### ISSUE THREAD

**Issue by jhyscode** [LYMDLUT/yolov5s-mobilenetv3#1]
大佬，打扰了，问一下你的残差块里面加了注意力模块，然后训练的VOC数据集，训练的时候需要加入YOLOv5官方提供的预训练权重吗，还是必须从头开始训练？

**Comment by LYMDLUT** [comment]
您好！十分抱歉由于过年最近没有登入github，耽误了您的实验进度。这个项目是一个ustc课题组的面试题目，有一定的价值。
由于网络结构更改较多，您可以在日志中看到，是不能够使用官方预训练权重的。Transferred 0/386 items from yolov5s.pt。
这个工程是基于yolov5 5.0 版本的，您依旧可以使用5.0的工程进行复现。由于yolov5目标检测框架的先进性，使用VOC从头训练即可实现收敛，如果追求更高精度，也可使用coco进行预训练。我也只是入门小白，如果有任何问题，欢迎您联系我。

**Comment by jhyscode** [comment]
非常感谢您的回复和解答，受教了！
